language: python
sudo: false

# Currently, cran-server only works on python 3.6
matrix:
  include:
      - os: linux
        python: 3.6

before_install:
  - .ci/setup.sh

# Install cran-server
install:
  - pip install .

# Test cran-server
script:
  - python -m pytest --cov
  - coverage report -m --fail-under=20

after_success:
  - echo "tests passed"
  - codecov
